### ISSUE TITLE
Issues with processing nil as input

### ISSUE THREAD

**Issue by okazymyrov** [logstash-plugins/logstash-filter-oui#6]
- Version:
 logstash-filter-oui-3.0.1

- Operating System:
Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux

- Config File (if you have sensitive info, please remove it):
```
input {
    generator {
        message => ", 2017-06-29 16:03:40, 44,  -1, OPN, ,   ,  -1,        0,        3,   0.  0.  0.  0,   0, , "
        count => 1
    }
}

filter {
    csv {
        columns => [ "BSSID","First time seen","Last time seen","channel","Speed","Privacy","Cipher","Authentication","Power","# beacons","# IV","LAN IP","ID-length","ESSID","Key" ]
    }

    oui {
        source => "BSSID"
        target => "BSSID OUI"
    }
}

output {
    stdout {
        codec => rubydebug
    }
}
```

- Sample Data:
In the above config.

- Steps to Reproduce:
/usr/share/logstash/bin/logstash -f ./example.conf

- Error 
```
10:08:21.101 [[main]>worker1] ERROR logstash.pipeline - Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `strip' for nil:NilClass", "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/oui-offline-1.2.7-java/lib/oui.rb:109:in `to_i'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/oui-offline-1.2.7-java/lib/oui.rb:97:in `find'", "/usr/share/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/oui-offline-1.2.7-java/lib/oui.rb:95:in `find'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-oui-3.0.1-java/lib/logstash/filters/oui.rb:33:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'", "(eval):68:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:370:in `filter_batch'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `each'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:369:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:350:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"]}
10:08:21.115 [LogStash::Runner] FATAL logstash.runner - An unexpected error occurred! {:error=>#<NoMethodError: undefined method `strip' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/oui-offline-1.2.7-java/lib/oui.rb:109:in `to_i'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/oui-offline-1.2.7-java/lib/oui.rb:97:in `find'", "/usr/share/logstash/vendor/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/oui-offline-1.2.7-java/lib/oui.rb:95:in `find'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-oui-3.0.1-java/lib/logstash/filters/oui.rb:33:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'", "(eval):68:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:370:in `filter_batch'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `each'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:369:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:350:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"]}
```

**Comment by jordansissel** [comment]
This is a bug.
